# SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

# Helper to append a missing dependency description to a global list.
function(_shadps4_mark_missing item)
    get_property(current GLOBAL PROPERTY SHADPS4_MISSING_SUBMODULES)
    if(NOT current)
        set(current "")
    endif()
    list(APPEND current "${item}")
    list(REMOVE_DUPLICATES current)
    set_property(GLOBAL PROPERTY SHADPS4_MISSING_SUBMODULES "${current}")
endfunction()

# Verify that a specific file exists relative to the source directory.
function(_shadps4_require_file relative_path description)
    if(NOT EXISTS "${CMAKE_SOURCE_DIR}/${relative_path}")
        _shadps4_mark_missing("${description} (${relative_path})")
    endif()
endfunction()

# Verify that a glob matches at least one file relative to the source directory.
function(_shadps4_require_glob relative_glob description)
    file(GLOB matches "${CMAKE_SOURCE_DIR}/${relative_glob}")
    if(matches)
        return()
    endif()
    _shadps4_mark_missing("${description} (${relative_glob})")
endfunction()

function(shadps4_verify_git_submodules)
    # Core dependencies that are always expected to be present.
    _shadps4_require_file("externals/cmake-modules/GetGitRevisionDescription.cmake" "CMake helper modules")
    _shadps4_require_file("externals/ext-boost/CMakeLists.txt" "Boost headers")
    _shadps4_require_file("externals/fmt/CMakeLists.txt" "fmt library")
    _shadps4_require_file("externals/ffmpeg-core/CMakeLists.txt" "FFmpeg core")
    _shadps4_require_glob("externals/LibAtrac9/C/src/*.c" "LibAtrac9 sources")
    _shadps4_require_file("externals/zlib-ng/CMakeLists.txt" "zlib-ng sources")
    _shadps4_require_file("externals/sdl3/CMakeLists.txt" "SDL3 sources")
    _shadps4_require_file("externals/vulkan-headers/CMakeLists.txt" "Vulkan headers")
    _shadps4_require_file("externals/vma/CMakeLists.txt" "Vulkan Memory Allocator")
    _shadps4_require_file("externals/glslang/CMakeLists.txt" "glslang sources")
    _shadps4_require_file("externals/robin-map/CMakeLists.txt" "tsl::robin_map sources")
    _shadps4_require_file("externals/xbyak/CMakeLists.txt" "xbyak sources")
    _shadps4_require_file("externals/magic_enum/CMakeLists.txt" "magic_enum sources")
    _shadps4_require_file("externals/toml11/CMakeLists.txt" "toml11 sources")
    _shadps4_require_file("externals/zydis/CMakeLists.txt" "Zydis sources")
    _shadps4_require_file("externals/sirit/CMakeLists.txt" "sirit sources")
    _shadps4_require_file("externals/libpng/CMakeLists.txt" "libpng sources")
    _shadps4_require_file("externals/tracy/CMakeLists.txt" "Tracy profiler sources")
    _shadps4_require_file("externals/pugixml/CMakeLists.txt" "pugixml sources")
    _shadps4_require_file("externals/ext-libusb/CMakeLists.txt" "libusb sources")
    _shadps4_require_file("externals/hwinfo/CMakeLists.txt" "HWInfo sources")
    _shadps4_require_file("externals/json/CMakeLists.txt" "nlohmann/json sources")
    _shadps4_require_file("externals/dear_imgui/imgui.cpp" "Dear ImGui sources")
    _shadps4_require_file("externals/xxhash/xxhash.c" "xxHash sources")
    _shadps4_require_file("externals/half/include/half.hpp" "half headers")

    if(ENABLE_DISCORD_RPC)
        _shadps4_require_file("externals/discord-rpc/CMakeLists.txt" "Discord RPC sources")
    endif()

    if(APPLE)
        _shadps4_require_file("externals/date/CMakeLists.txt" "date library")
        _shadps4_require_file("externals/MoltenVK/CMakeLists.txt" "MoltenVK sources")
        _shadps4_require_file("externals/epoll-shim/CMakeLists.txt" "epoll-shim sources")
    endif()

    if(WIN32)
        _shadps4_require_file("externals/ext-wepoll/CMakeLists.txt" "wepoll sources")
    endif()

    get_property(missing GLOBAL PROPERTY SHADPS4_MISSING_SUBMODULES)
    if(missing)
        list(REMOVE_DUPLICATES missing)
        string(JOIN "\n  - " missing_formatted ${missing})
        message(FATAL_ERROR "Missing required git submodules:\n  - ${missing_formatted}\n" "Please run 'git submodule update --init --recursive' and retry.")
    endif()
endfunction()
